/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FoodTruck_Bill;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

public class UpdateInfo extends javax.swing.JFrame {

    /**
     * Creates new form UpdateInfo
     */
    public UpdateInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlbChicken = new javax.swing.JLabel();
        jlbCheese = new javax.swing.JLabel();
        jlbTikki = new javax.swing.JLabel();
        jlbZinger = new javax.swing.JLabel();
        jlbCola = new javax.swing.JLabel();
        jlbCoffee = new javax.swing.JLabel();
        jlbTea = new javax.swing.JLabel();
        jlbColdCoffee = new javax.swing.JLabel();
        jlbIceTea = new javax.swing.JLabel();
        jlbBanana = new javax.swing.JLabel();
        jlbChoco = new javax.swing.JLabel();
        jlbTax = new javax.swing.JLabel();
        jlbDelivery = new javax.swing.JLabel();
        jtxtChicken = new javax.swing.JTextField();
        jtxtCheese = new javax.swing.JTextField();
        jtxtTikki = new javax.swing.JTextField();
        jtxtZinger = new javax.swing.JTextField();
        jtxtCola = new javax.swing.JTextField();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtTea = new javax.swing.JTextField();
        jtxtColdCoffee = new javax.swing.JTextField();
        jtxtIceTea = new javax.swing.JTextField();
        jtxtBanana = new javax.swing.JTextField();
        jtxtChoco = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtDelivery = new javax.swing.JTextField();
        JBtnUpdate = new javax.swing.JButton();
        jBtnPrice = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITEMS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EXISTING PRICE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NEW PRICE");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Chicken Burger");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cheese Burger");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("McAloo Tikki");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Zinger Burger");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cola");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Coffee");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tea");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cold Coffee");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ice Tea");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tax");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Home Delivery");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Banana Shake");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Chocolate Shake");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbChicken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbChicken.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbCheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbCheese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCheese.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbTikki.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTikki.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTikki.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbZinger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbZinger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbZinger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbCola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbCola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbCoffee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbColdCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbColdCoffee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbColdCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbIceTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbIceTea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIceTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbBanana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbBanana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBanana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbChoco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbChoco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbChoco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbDelivery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChicken.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtChicken.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtCheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCheese.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCheese.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtTikki.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTikki.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTikki.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtZinger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtZinger.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtZinger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtCola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCola.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtColdCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtColdCoffee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtColdCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtIceTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtIceTea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtIceTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtBanana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBanana.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtBanana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtChoco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChoco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtChoco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDelivery.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        JBtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBtnUpdate.setText("Update");
        JBtnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnUpdateMouseClicked(evt);
            }
        });
        JBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnUpdateActionPerformed(evt);
            }
        });

        jBtnPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnPrice.setText("Existing Price");
        jBtnPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnPriceMouseClicked(evt);
            }
        });
        jBtnPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPriceActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton1)))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addComponent(jlbChicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbCheese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbTikki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbZinger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbColdCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbIceTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbBanana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbChoco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBtnPrice)))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(jtxtChicken)
                        .addComponent(jtxtCheese)
                        .addComponent(jtxtTikki)
                        .addComponent(jtxtZinger)
                        .addComponent(jtxtCola)
                        .addComponent(jtxtCoffee)
                        .addComponent(jtxtTea)
                        .addComponent(jtxtColdCoffee)
                        .addComponent(jtxtIceTea)
                        .addComponent(jtxtBanana)
                        .addComponent(jtxtChoco)
                        .addComponent(jtxtTax)
                        .addComponent(jtxtDelivery)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addGroup(layout.createSequentialGroup()
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                            .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                    .addComponent(jLabel3)
                                                                                                    .addComponent(jLabel2)
                                                                                                    .addComponent(jLabel1))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                    .addComponent(jtxtChicken)
                                                                                                    .addComponent(jlbChicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                    .addComponent(jlbCheese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                                            .addComponent(jtxtCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGap(18, 18, 18)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                            .addComponent(jLabel6)
                                                                                            .addComponent(jlbTikki, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                    .addComponent(jtxtTikki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                    .addComponent(jlbZinger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                    .addComponent(jtxtZinger, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                    .addComponent(jlbCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                            .addComponent(jtxtCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                            .addComponent(jlbCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel10)
                                                                    .addComponent(jlbTea, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addComponent(jtxtTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jlbColdCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addComponent(jtxtColdCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jlbIceTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(jtxtIceTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlbBanana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jtxtBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbChoco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jtxtChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtxtDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnUpdate)
                    .addComponent(jBtnPrice)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPriceMouseClicked
        try {
            FoodTruck s = new FoodTruck();
            String s1 = String.format("%.2f",s.costChicken);
            String s2 = String.format("%.2f",s.costCheese);
            String s3 = String.format("%.2f",s.costTikki);
            String s4 = String.format("%.2f",s.costZinger);
            String s5 = String.format("%.2f",s.cola);
            String s6 = String.format("%.2f",s.coffee);
            String s7 = String.format("%.2f",s.Tea);
            String s8 = String.format("%.2f",s.coldCoffee);
            String s9 = String.format("%.2f",s.iceTea);
            String s10 = String.format("%.2f",s.banana);
            String s11 = String.format("%.2f",s.choco);
            String s12 = String.format("%.2f",s.tax);
            String s13 = String.format("%.2f",s.del);
            jlbChicken.setText(s1);
            jlbCheese.setText(s2);
            jlbTikki.setText(s3);
            jlbZinger.setText(s4);
            jlbCola.setText(s5);
            jlbCoffee.setText(s6);
            jlbTea.setText(s7);
            jlbColdCoffee.setText(s8);
            jlbIceTea.setText(s9);
            jlbBanana.setText(s10);
            jlbChoco.setText(s11);
            jlbTax.setText(s12);
            jlbDelivery.setText(s13);
        } catch (IOException ex) {
            Logger.getLogger(UpdateInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnPriceMouseClicked

    @SuppressWarnings("static-access")
    private void JBtnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnUpdateMouseClicked
        try {
            FoodTruck s = new FoodTruck();
            boolean s1 = jtxtChicken.getText().isEmpty();
            boolean s2 = jtxtCheese.getText().isEmpty();
            boolean s3 = jtxtTikki.getText().isEmpty();
            boolean s4 = jtxtZinger.getText().isEmpty();
            boolean s5 = jtxtCola.getText().isEmpty();
            boolean s6 = jtxtCoffee.getText().isEmpty();
            boolean s7 = jtxtTea.getText().isEmpty();
            boolean s8 = jtxtColdCoffee.getText().isEmpty();
            boolean s9 = jtxtIceTea.getText().isEmpty();
            boolean s10 = jtxtBanana.getText().isEmpty();
            boolean s11 = jtxtChoco.getText().isEmpty();
            boolean s12 = jtxtTax.getText().isEmpty();
            boolean s13 = jtxtDelivery.getText().isEmpty();
            FileWriter writer = new FileWriter("F:\\NETBEAN PROJECTS\\Bill System\\src\\FoodTruck_Bill\\Info2");
            BufferedWriter bw = new BufferedWriter(writer);
            
            if(!s1)
            {
                bw.write(jtxtChicken.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.costChicken);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s2)
            {
                bw.write(jtxtCheese.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.costCheese);
            bw.write(v1);
            bw.write('\n');
            }
            
            
            if(!s3)
            {
                bw.write(jtxtTikki.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.costTikki);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s4)
            {
                bw.write(jtxtZinger.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.costZinger);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s5)
            {
                bw.write(jtxtCola.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.cola);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s6)
            {
                bw.write(jtxtCoffee.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.coffee);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s7)
            {
                bw.write(jtxtTea.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.Tea);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s8)
            {
                bw.write(jtxtColdCoffee.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.coldCoffee);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s9)
            {
                bw.write(jtxtIceTea.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.iceTea);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s10)
            {
                bw.write(jtxtBanana.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.banana);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s11)
            {
                bw.write(jtxtChoco.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.choco);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s12)
            {
                bw.write(jtxtTax.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.tax);
            bw.write(v1);
            bw.write('\n');
            }
            
            if(!s13)
            {
                bw.write(jtxtDelivery.getText());
                bw.write('\n');
            }
            else
            {
                 String v1 = String.format("%.2f", s.del);
            bw.write(v1);
            bw.write('\n');
            }
            bw.close();
            FoodTruck temp = new FoodTruck();
        } catch (IOException ex) {
            Logger.getLogger(UpdateInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtnUpdateMouseClicked

    private void JBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnUpdateActionPerformed

    private void jBtnPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jlbChicken.setText(null);
        jlbCheese.setText(null);
        jlbTikki.setText(null);
        jlbZinger.setText(null);
        jlbCola.setText(null);
        jlbCoffee.setText(null);
        jlbTea.setText(null);
        jlbColdCoffee.setText(null);
        jlbIceTea.setText(null);
        jlbBanana.setText(null);
        jlbChoco.setText(null);
        jlbTax.setText(null);
        jlbDelivery.setText(null);
        jtxtChicken.setText(null);
        jtxtCheese.setText(null);
        jtxtTikki.setText(null);
        jtxtZinger.setText(null);
        jtxtCola.setText(null);
        jtxtCoffee.setText(null);
        jtxtTea.setText(null);
        jtxtColdCoffee.setText(null);
        jtxtIceTea.setText(null);
        jtxtBanana.setText(null);
        jtxtChoco.setText(null);
        jtxtTax.setText(null);
        jtxtDelivery.setText(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnUpdate;
    private javax.swing.JButton jBtnPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlbBanana;
    private javax.swing.JLabel jlbCheese;
    private javax.swing.JLabel jlbChicken;
    private javax.swing.JLabel jlbChoco;
    private javax.swing.JLabel jlbCoffee;
    private javax.swing.JLabel jlbCola;
    private javax.swing.JLabel jlbColdCoffee;
    private javax.swing.JLabel jlbDelivery;
    private javax.swing.JLabel jlbIceTea;
    private javax.swing.JLabel jlbTax;
    private javax.swing.JLabel jlbTea;
    private javax.swing.JLabel jlbTikki;
    private javax.swing.JLabel jlbZinger;
    private javax.swing.JTextField jtxtBanana;
    private javax.swing.JTextField jtxtCheese;
    private javax.swing.JTextField jtxtChicken;
    private javax.swing.JTextField jtxtChoco;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtCola;
    private javax.swing.JTextField jtxtColdCoffee;
    private javax.swing.JTextField jtxtDelivery;
    private javax.swing.JTextField jtxtIceTea;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTea;
    private javax.swing.JTextField jtxtTikki;
    private javax.swing.JTextField jtxtZinger;
    // End of variables declaration//GEN-END:variables
}
